version: '3.10'



services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/containers/postgres.Dockerfile
    container_name: django_db
    restart: always
    env_file:
      - ./docker/envs/.env
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: docker/containers/api.Dockerfile
    container_name: django_api
    volumes:
      - .:/pom-54-team-12
    command: pom-54-team-12/docker/scripts/api.entrypoint.dev.sh
    env_file:
      - ./docker/envs/.env
    ports:
      - "8000:8000"  #
      - "8080:8080"  # port for pycharm server
    depends_on:
      - postgres
